import Foundation

public class Texts {
    public let presentetionTexts = ["Opa! Me chamo João e acredito que você possa me ajudar. (;\nEu estava andando em um parque e acabei me perdendo.\nEu até estou usando meu celular para encontrar o caminho de casa, mas tem alguém me perseguindo...", "Pelo o que eu consegui perceber, quem está me perseguindo quer roubar todos os meus dados. \nEu estou assustado porque não quero minhas informações com um desconhecido...", "Preciso que você me ajude a despitá-lo!\nEu tenho que aumentar meu nível de segurança para conseguir fugir. Para isso, você precisa responder algumas perguntas...", "Mas cuidado! 3 respostas erradas significam a perda de todos os meus dados.\nPronto para me ajudar?"]
    
    public let questionTexts = ["Você acabou de baixar um novo aplicativo que consegue mostrar como o seu rosto vai ficar daqui a 30 anos, mas ele está pedindo permissão de acesso a sua localização e contatos. O que você deve fazer?","Você recebe uma mensagem sobre um sorteio imperdível para ganhar dinheiro, mas para participar é necessário informar alguns dados pessoais, como CPF. Como você procede?","Você é convidado por um amigo a participar de um quiz \"Saiba quem você é no Big Brother Brasil\". Como esse quiz pode colocá-lo em risco?", "Você está jogando um simulador de café online que te dá a chance de ganhar 50 moedas caso você responda um questionário sobre sua preferência de roupas. Por que um jogo se importaria com isso?", "Lendo um jornal você descobre que a maioria dos sites de pesquisa gravam tudo o que você procura. Como você pode realizar buscas na internet sem ser rastreado?", "Na sua rede social aparece uma sugestão de amizade de uma pessoa que você conheceu recentemente em uma festa. Como a rede social soube que vocês se conheceram?", "Escolher senhas fortes é importante para a segurança das nossas contas online, mas as vezes é fácil esquecê-las. Qual é a melhor forma de guardar digitalmente as senhas de suas contas?", "Você decide que não quer mais ser rastreado digitalmente e, por isso, começa a usar seu navegador no modo anônimo. Como essa ação pode te deixar mais seguro?", "Você percebe que na sua rede social está aparecendo anúncios de produtos que você pesquisou em outros locais. É possível que essa rede social esteja coletando os seus dados em algum outro serviço digital?", "Após postar umas fotos de sua viagem, você começa a receber anúncios de um restaurante nesse local. Como os anunciantes conseguem saber onde você está por meio da foto?", "Em 2020 está previsto para a Lei Geral de Proteção de Dados (LGPD) entrar em vigor no Brasil. Do que isso se trata?", "Após visitar um loja física, você começa a receber anúncios dela mesmo sem ter dado nenhum dado seu. Como você pode evitar que isso aconteça?", "Todo aplicativo instalado em seu celular coleta dados do usuário, porém as informações coletadas diferem. Qual é a melhor forma de saber quais são os seus dados coletados por um aplicativo?","Você deletou sua conta de uma rede social. Após um tempo, decide voltar com uma conta nova, mas percebe que você recebe o mesmo conteúdo que recebia na conta antiga. Por que isso acontece?", "Nos termos de privacidade dos serviços online é informado quais são os dados coletados de seus usuários. As empresas de tecnologia precisam de autorização para compartilharem esses dados?"]
    
    public let firstQuestionButtonTexts = ["Digo sim a todas as permissões, até porque todo os meus amigos estão usando o aplicativo", "Realizo o cadastro, porque é uma ótima chance de ganhar dinheiro", "Posso ficar enfurecido com o resultado e espalhar meus dados pela internet", "Provavelmente porque eles querem construir roupas no jogo semelhantes com a que eu gosto", "Realizando a pesquisa em outra língua, como o espanhol", "Provavelmente a sugestão de amizade foi apenas uma coincidência e isso não deve acontecer novamente", "Usando um serviço de senhas que criptografe os dados dos usuários e possua um fator duplo de autenticação", "Essa ação não aumenta a segurança do usuário, uma vez que os computadores são rastreados por meio de \"impressão digital\"", "Não, as redes sociais apenas coletam dados gerados em seus serviços", "Alguém do restaurante viu minha imagem e decidiu me direcionar o anúncio", "Lei que proibirá o uso de \"impressão digital\" como meio de rastreamento de dados", "Deixando de visitar lojas do mesmo segmento", "Lendo os termos  de uso desse aplicativo, além de pesquisar pelas configurações de privacidade que o aplicativo oferece", "Porque eu usei o mesmo e-mail para conta nova", "Por enquanto, não. Mas será necessário após a Lei Geral de Proteção de Dados Pessoais entrar em vigor"]

    public let secondQuestionButtonTexts = ["Tento descobrir se consigo usar o aplicativo sem dar permissão a todos os dados pedidos", "Faço o cadastro no site para participar do sorteio, mas coloco dados falsos", "O criador do quiz pode enviar as minhas respostas para terceiros, como redes sociais e anunciantes", "É parte do jogo, só assim ele não fica tão fácil", "Utilizando a navegação anônima do navegador de internet - assim o buscador não consegue salvar meus dados", "No geral, redes sociais coletam dados de localização de seus usuários e por isso ela sabia que estávamos na mesma festa", "Salvando em algum aplicativo de notas digital, como o Google Docs ou Evernote", "Navegar no modo anônimo impede o rastreamento porque não salva o histórico no computador", "Sim, mas é necessário ter uma conta na rede social para que ela possa coletar os meus dados", "A geolocalização das minhas fotos está ativada e, por isso, todas as fotos que tiro informam onde estou", "Legislação que tornará os dados sensíveis do governo confidenciais", "Substituindo as compras em lojas físicas por lojas que são apenas virtuais", "Não é possível saber quais são os meus dados coletados", "Porque minha senha atual é igual a da conta antiga", "Sim e, além disso, nos termos de uso é necessário explicitar com quem os meus dados estão sendo compartilhados"]
    
    public let thirdQuestionButtonTexts = ["Desligo o GPS enquanto usa o aplicativo, assim ele não terá acesso a minha localização", "Marco a mensagem como SPAM e bloqueio quem enviou. Provavelmente o site deve conter vírus ou pretende vender os meus dados do cadastro", "Na verdade, esse tipo de quiz não oferece nenhum risco aos meus dados", "Para vender minhas respostas a anunciantes online", "Usando serviços de busca que não coletam dados, como DuckDuckGo", "Porque a pessoa que eu acabei de conhecer postou uma foto dela na festa", "A melhor forma é utilizar uma senha para todas as contas e não precisar digitar em nenhuma mídia digital", "Na verdade, o modo anônimo não me impede de ser rastreado por causa do meu histórico salvo no modo não anônimo", "Sim. Mesmo se eu não possuir uma conta nessa rede social, eu consigo ser rastreado e ter meus dados coletados", "O restaurante deve estar enviando anúncios para pessoas de outras cidades para se promover", "Lei que regulamenta como os dados das pessoas serão recolhidos, tratados e compartilhados", "Deixando o GPS do celular desligado quando não estiver sendo usando, além de conferir as configurações de privacidade do meu celular", "Perguntando a um amigo seu que também use esse aplicativo", "Porque, mesmo excluindo minha conta, a rede social ainda armazena os meus dados","Não, mas é necessário informar para que fim meus dados estão sendo usados"]
    
    public init() {}
}
