import Foundation

public class Texts {
    public let presentetionTexts = ["Opa! Me chamo João e acredito que você possa me ajudar. (;\nEu estava andando em um parque e acabei me perdendo.\nEu até estou usando meu celular para encontrar o caminho de casa, mas tem alguém me perseguindo...", "Pelo o que eu consegui perceber, quem está me perseguindo quer roubar todos os meus dados. \nEu estou assustado porque não quero minhas informações com um desconhecido...", "Preciso que você me ajude a despitá-lo!\nEu tenho que aumentar meu nível de segurança para conseguir fugir. Para isso, você precisa responder algumas perguntas...", "Mas cuidado! 3 respostas erradas significam a perda de todos os meus dados.\nPronto para me ajudar?"]
    
    public let questionTexts = ["Você é convidado a participar de um quiz \"Saiba quem você é no BBB\". Como esse quiz pode colocá-lo em risco ?", "Você está jogando um simulador de café online que te dá a chance de ganhar 50 moedas novas caso você responda um questionário sobre sua preferência de roupas. Por que um jogo se importaria com isso?", "Você acabou de baixar um novo aplicativo que consegue mostrar como o seu rosto vai ficar daqui a 30 anos, mas ele está pedindo permissão de acesso a sua localização e contatos. O que você deve fazer?", "A maioria dos sites de pesquisa gravam tudo o que você procura. Como você pode realizar buscas sem ser rastreado?", "Você recebe uma mensagem sobre um sorteio imperdível para ganhar dinheiro, mas para participar você precisa realizar um cadastro que pede alguns dados, como CPF. Como você procede?", "Na sua rede social aparece uma sugestão de amizade de uma pessoa que você conheceu recentemente em uma festa. Como a rede social soube que vocês se conheceram?", "Qual é a melhor forma de guardar digitalmente as senhas de suas contas online?", "Você decide que não quer mais ser rastreado digitalmente e começa a usar seu navegador no modo anônimo. Como essa ação pode te deixar mais seguro?", "É possível uma rede social coletar os seus dados em algum outro serviço digital que você esteja usando?", "Após postar umas fotos de sua viagem, você começa a receber anúncios de um restaurante nesse local. Como os anunciantes conseguem saber onde você está por meio da foto?", "Em 2020 está previsto para a Lei Geral de Proteção de Dados (LGPD) entrar em vigor. Do que isso se trata?", "As empresas de tecnologia precisam da sua autorização para compartilharem seus dados?", "Você deletou sua conta de uma rede social. Após um tempo, decide voltar com uma conta nova, mas percebe que você recebe o mesmo conteúdo que recebia na conta antiga. Por que isso acontece?", "Qual é a melhor forma de saber quais são os seus dados coletados por um aplicativo?", "Após visitar um loja física, você começa a receber anúncios dela mesmo sem ter dado nenhum dado seu. Como você pode evitar que isso aconteça?"]
    
    public let firstQuestionButtonTexts = ["Você pode ficar enfurecido com o resultado e espalhar seus dados pela internet", "Porque eles querem construir roupas no jogo semelhantes com a que você gosta", "Tentar descobrir se você consegue usar o aplicativo sem dar permissão a esses dados", "Realizando a pesquisa em outra língua, como o espanhol", "Realiza o cadastro, porque é uma ótima chance de ganhar dinheiro", "Provavelmente a sugestão de amizade foi apenas uma coincidência e isso não deve acontecer novamente", "Salvando em algum aplicativo de notas digital, como o Google Docs ou Evernote", "Essa ação não aumenta a segurança do usuário, uma vez que os computadores são rastreados por meio de \"impressão digital\"", "Não, as redes sociais apenas coletam dados gerados em seus serviços", "Alguém do restaurante viu sua imagem e decidiu direcionar o anúncio a você", "Lei que irá proibir o uso de \"impressão digital\" como meio de rastreamento de dados 1", "Por enquanto, não. Mas será necessário após a Lei Geral de Proteção de Dados Pessoais entrar em vigor", "Porque você usou o mesmo e-mail para conta nova", "Lendo os termos  de uso desse aplicativo, além de pesquisar pelas configurações de privacidade que o aplicativo oferece", "Deixando de visitar lojas do mesmo segmento"]
    
    public let secondQuestionButtonTexts = ["O criador do quiz pode enviar as suas respostas para terceiros, como redes sociais e anunciantes", "É parte do jogo, só assim ele não fica tão fácil", "Dizer sim a todas as permissões, até porque todo mundo está usando o aplicativo", "Utilizando a navegação anônima do navegador de internet - assim o buscador não consegue salvar os dados", "Marca a mensagem como SPAM e bloqueia quem enviou. Provavelmente o site deve conter vírus ou pretende vender os dados do cadastro.", "No geral, redes sociais coletam dados de localização de seus usuários e por isso ela sabia que vocês estavam na mesma festa", "A melhor forma é utilizar uma senha para todas as contas e não precisar digitar em nenhuma mídia digital", "Navegar no modo anônimo impede o rastreamento porque não salva o histórico no computador", "Sim, mas é necessário ter uma conta na rede social para que ela possa os meus dados", "Você permite a geolocalização das suas fotos e, por isso, todas as fotos que você tira informam onde você está", "Legislação que tornará os dados sensíveis do governo confidenciais", "Sim e, além disso, nos termos de uso é necessário explicitar com quem os meus dados estão sendo compartilhados", "Porque sua senha era a mesma da antiga conta", "Não é possível saber quais são os meus dados coletados", "Substituindo as compras em lojas físicas por lojas que são apenas virtuais"]
    
    public let thirdQuestionButtonTexts = ["Na verdade, esse tipo de quiz não oferece nenhum risco aos meus dados", "Para vender suas respostas a anunciantes online", "Desligar o GPS enquanto usa o aplicativo, assim ele não terá acesso a sua localização", "Usando serviços de busca que não coletam dados, como DuckDuckGo", "Faz o cadastro no site para participar do sorteio, mas coloca dados falsos", "Porque a pessoa que você conheceu postou uma foto dela na festa", "Usando um serviço de senhas que criptografe os dados dos usuários e possua um fator duplo de autenticação", "Na verdade, o modo anônimo não me impede de ser rastreado por causa do meu histórico salvo no modo não anônimo", "Sim. Mesmo se eu não possuir uma conta nessa rede social, eu consigo ser rastreado e ter meus dados coletados", "O restaurante está enviando anúncios para pessoas de outras cidades para se promover", "Lei que regulamenta como os dados das pessoas serão recolhidos, tratados e compartilhados", "Não, mas é necessário informar para que fim meus dados estão sendo usados", "Porque, mesmo excluindo sua conta, a rede social ainda armazena os seus dados", "Perguntando a um amigo seu que também use esse aplicativo", "Deixando o GPS do celular desligado quando não estiver sendo usando, além de conferir as configurações de privacidade do meu celular"]
    
    public init() {}
}
